"""
Scans the 'images' folder (next to this script) and writes image-list.js
with the current list of filenames. Run this once, and again anytime you
add or remove photos.

Usage:
    python generate-list.py
    (or) python3 generate-list.py
"""

import os
import json

IMAGES_DIR = "images"
OUTPUT_FILE = "image-list.js"
VALID_EXT = {".jpg", ".jpeg", ".png", ".gif", ".webp", ".bmp", ".svg"}

def main():
    if not os.path.isdir(IMAGES_DIR):
        print(f"Couldn't find a folder named '{IMAGES_DIR}' next to this script.")
        print("Create it and put your photos inside, then run this script again.")
        return

    files = sorted(
        f for f in os.listdir(IMAGES_DIR)
        if os.path.splitext(f)[1].lower() in VALID_EXT
    )

    with open(OUTPUT_FILE, "w") as f:
        f.write("// Auto-generated by generate-list.py — do not edit by hand.\n")
        f.write("// Run generate-list.py whenever you add or remove photos in the images folder.\n")
        f.write("const imageList = " + json.dumps(files, indent=2) + ";\n")

    print(f"Found {len(files)} image(s). Wrote {OUTPUT_FILE}.")

if __name__ == "__main__":
    main()
